apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts.fullname" . }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "charts.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: "TOKEN"
            valueFrom:
              secretKeyRef:
                key:  botToken
                name: {{ .Release.Name }}-auth
          - name: "MONGO_HOST"
            valueFrom:
              secretKeyRef:
                key:  mongoHostname
                name: {{ .Release.Name }}-auth
          - name: "MONGO_USER"
            valueFrom:
              secretKeyRef:
                key:  mongoUsername
                name: {{ .Release.Name }}-auth
          - name: "MONGO_PASS"
            valueFrom:
              secretKeyRef:
                key:  mongoPassword
                name: {{ .Release.Name }}-auth
          - name: "MONGO_DB"
            valueFrom:
              secretKeyRef:
                key:  mongoDatabase
                name: {{ .Release.Name }}-auth
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
